# fly.toml app configuration file generated for marimo-gliner-dry-darkness-706 on 2024-12-24T22:22:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'marimo-gliner-dry-darkness-706'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
